import { describe, expect, it } from 'vitest'
import { projectToUpsert, rowToProject } from './projectMapper'
import type { Project, SupabaseProjectRow } from '../types/project'

const row: SupabaseProjectRow = {
  id: 'project-1',
  slug: 'ai-task-planner',
  title_zh: 'AI 任务规划助手',
  title_en: 'AI Task Planner',
  category_zh: 'AI 应用',
  category_en: 'AI App',
  status: 'Building',
  kind: 'case-study',
  featured: true,
  published: true,
  sort_order: 10,
  role_zh: '个人项目',
  role_en: 'Solo project',
  stage_zh: '任务规划流程',
  stage_en: 'Task-planning flow',
  description_zh: '把目标拆成任务。',
  description_en: 'Turn goals into tasks.',
  problem_zh: '目标太模糊。',
  problem_en: 'Goals are fuzzy.',
  approach_zh: '生成结构化任务。',
  approach_en: 'Generate structured tasks.',
  outcome_zh: '形成可编辑计划。',
  outcome_en: 'Editable plan.',
  highlights: [{ zh: '结构化任务', en: 'Structured tasks' }],
  next_steps: [{ zh: '项目复盘', en: 'Writeup' }],
  stack: [{ zh: 'React', en: 'React' }],
  demo_url: 'https://example.com/demo',
  repo_url: null,
  cover_url: null,
  gradient: 'from-[#b8f05a] via-[#4fd1c5] to-[#2f7df6]',
}

describe('projectMapper', () => {
  it('maps a Supabase row into the public project model', () => {
    expect(rowToProject(row)).toEqual({
      id: 'project-1',
      slug: 'ai-task-planner',
      title: { zh: 'AI 任务规划助手', en: 'AI Task Planner' },
      category: { zh: 'AI 应用', en: 'AI App' },
      status: 'Building',
      kind: 'case-study',
      featured: true,
      published: true,
      sortOrder: 10,
      role: { zh: '个人项目', en: 'Solo project' },
      stage: { zh: '任务规划流程', en: 'Task-planning flow' },
      description: { zh: '把目标拆成任务。', en: 'Turn goals into tasks.' },
      problem: { zh: '目标太模糊。', en: 'Goals are fuzzy.' },
      approach: { zh: '生成结构化任务。', en: 'Generate structured tasks.' },
      outcome: { zh: '形成可编辑计划。', en: 'Editable plan.' },
      highlights: [{ zh: '结构化任务', en: 'Structured tasks' }],
      nextSteps: [{ zh: '项目复盘', en: 'Writeup' }],
      stack: [{ zh: 'React', en: 'React' }],
      demoUrl: 'https://example.com/demo',
      repoUrl: undefined,
      coverUrl: undefined,
      gradient: 'from-[#b8f05a] via-[#4fd1c5] to-[#2f7df6]',
    })
  })

  it('maps a public project model into a Supabase upsert payload', () => {
    const project: Project = {
      id: 'project-1',
      slug: 'ai-task-planner',
      title: { zh: 'AI 任务规划助手', en: 'AI Task Planner' },
      category: { zh: 'AI 应用', en: 'AI App' },
      status: 'Building',
      kind: 'case-study',
      featured: true,
      published: true,
      sortOrder: 10,
      role: { zh: '个人项目', en: 'Solo project' },
      stage: { zh: '任务规划流程', en: 'Task-planning flow' },
      description: { zh: '把目标拆成任务。', en: 'Turn goals into tasks.' },
      problem: { zh: '目标太模糊。', en: 'Goals are fuzzy.' },
      approach: { zh: '生成结构化任务。', en: 'Generate structured tasks.' },
      outcome: { zh: '形成可编辑计划。', en: 'Editable plan.' },
      highlights: [{ zh: '结构化任务', en: 'Structured tasks' }],
      nextSteps: [{ zh: '项目复盘', en: 'Writeup' }],
      stack: [{ zh: 'React', en: 'React' }],
      demoUrl: 'https://example.com/demo',
      gradient: 'from-[#b8f05a] via-[#4fd1c5] to-[#2f7df6]',
    }

    expect(projectToUpsert(project)).toEqual({
      id: 'project-1',
      slug: 'ai-task-planner',
      title_zh: 'AI 任务规划助手',
      title_en: 'AI Task Planner',
      category_zh: 'AI 应用',
      category_en: 'AI App',
      status: 'Building',
      kind: 'case-study',
      featured: true,
      published: true,
      sort_order: 10,
      role_zh: '个人项目',
      role_en: 'Solo project',
      stage_zh: '任务规划流程',
      stage_en: 'Task-planning flow',
      description_zh: '把目标拆成任务。',
      description_en: 'Turn goals into tasks.',
      problem_zh: '目标太模糊。',
      problem_en: 'Goals are fuzzy.',
      approach_zh: '生成结构化任务。',
      approach_en: 'Generate structured tasks.',
      outcome_zh: '形成可编辑计划。',
      outcome_en: 'Editable plan.',
      highlights: [{ zh: '结构化任务', en: 'Structured tasks' }],
      next_steps: [{ zh: '项目复盘', en: 'Writeup' }],
      stack: [{ zh: 'React', en: 'React' }],
      demo_url: 'https://example.com/demo',
      repo_url: null,
      cover_url: null,
      gradient: 'from-[#b8f05a] via-[#4fd1c5] to-[#2f7df6]',
    })
  })
})
