insert into public.portfolio_projects (
  slug,
  title_zh,
  title_en,
  category_zh,
  category_en,
  status,
  kind,
  featured,
  published,
  sort_order,
  role_zh,
  role_en,
  stage_zh,
  stage_en,
  description_zh,
  description_en,
  problem_zh,
  problem_en,
  approach_zh,
  approach_en,
  outcome_zh,
  outcome_en,
  highlights,
  next_steps,
  stack,
  demo_url,
  repo_url,
  cover_url,
  gradient
) values (
  'ai-task-planner',
  'AI 任务规划助手',
  'AI Task Planner',
  'AI 应用',
  'AI App',
  'Building',
  'case-study',
  true,
  true,
  10,
  '个人项目 / 产品设计与前端实现',
  'Solo project / Product design and front-end implementation',
  '任务规划流程与交互原型',
  'Task-planning flow and interactive prototype',
  '在基础待办的任务管理场景上，加入目标拆解、任务生成和计划确认，让用户从一个目标进入可执行清单。',
  'A planning workflow that turns fuzzy goals into editable task plans.',
  '普通待办只能记录任务，不能帮助用户把一个模糊目标拆成可执行路径。',
  'A basic todo list records tasks, but does not help users turn fuzzy goals into an executable path.',
  '用 AI 生成结构化任务，再让用户编辑、排序和确认优先级，把模型输出变成可调整的计划草稿。',
  'Use AI to create structured tasks, then let users edit, reorder, and confirm priorities.',
  '当前版本呈现任务拆解、编辑确认和状态流转，展示从需求到界面实现的完整思路。',
  'The current version focuses on task breakdown, editable review, and status flow for an AI-assisted task planner.',
  '[{"zh":"梳理从输入目标到确认计划的完整用户路径。","en":"Mapped the full path from goal input to plan review."},{"zh":"用结构化数据组织任务、优先级、状态和行动建议。","en":"Modeled tasks, priority, status, and action suggestions as structured data."}]'::jsonb,
  '[{"zh":"补充真实运行截图和任务编辑状态。","en":"Add runtime screenshots and task editing states."}]'::jsonb,
  '[{"zh":"React","en":"React"},{"zh":"TypeScript","en":"TypeScript"},{"zh":"Supabase","en":"Supabase"},{"zh":"提示词设计","en":"Prompt Design"}]'::jsonb,
  null,
  null,
  null,
  'from-[#b8f05a] via-[#4fd1c5] to-[#2f7df6]'
) on conflict (slug) do update set
  title_zh = excluded.title_zh,
  title_en = excluded.title_en,
  category_zh = excluded.category_zh,
  category_en = excluded.category_en,
  status = excluded.status,
  kind = excluded.kind,
  featured = excluded.featured,
  published = excluded.published,
  sort_order = excluded.sort_order,
  role_zh = excluded.role_zh,
  role_en = excluded.role_en,
  stage_zh = excluded.stage_zh,
  stage_en = excluded.stage_en,
  description_zh = excluded.description_zh,
  description_en = excluded.description_en,
  problem_zh = excluded.problem_zh,
  problem_en = excluded.problem_en,
  approach_zh = excluded.approach_zh,
  approach_en = excluded.approach_en,
  outcome_zh = excluded.outcome_zh,
  outcome_en = excluded.outcome_en,
  highlights = excluded.highlights,
  next_steps = excluded.next_steps,
  stack = excluded.stack,
  demo_url = excluded.demo_url,
  repo_url = excluded.repo_url,
  cover_url = excluded.cover_url,
  gradient = excluded.gradient;
